### ISSUE TITLE
ESP8266-01 compatibility

### ISSUE THREAD

**Issue by rafik73github** [lpaseen/ht16k33#5]
For the library to work correctly on ESP8266-01 it should be in the file ht16k33.cpp
line
`Wire.begin();`
 and change to 
`Wire.begin(0,2);`

Regards

**Comment by lpaseen** [comment]
Currently on vacation but I will test it once I'm back (end of august)

**Comment by adamm** [comment]
This must have been a quirk with the esp8266's i2c implementation last year, as when I use this library on the same chip with updated SDK 2.2.1(cfd48f3), `Wire.begin()` is all that's required.

**Comment by lpaseen** [comment]
That sounds good because I totally forgot about this and now when I was going to check on it I realize it will take a while since I need to setup something to test with.
