### ISSUE TITLE
Wrong Test in "setBrightness"

### ISSUE THREAD

**Issue by rolfn** [lpaseen/ht16k33#7]
The `setBrightness` function (line 345 in the file `ht16k33.cpp`) contains the following test:

```
if (HT16K33_DIM_1>=0 && level <HT16K33_DIM_16){
```

Should it be correct as follows?

```
if (level >= HT16K33_DIM_1 && level <HT16K33_DIM_16){
```

**Comment by lpaseen** [comment]
Yes, that seems to be a bug/typo, no point in checking a constant.
